const mockMaps = [
  {
    name: "Gran Chaco",
    type: "map",
    favorite: true,
    imageLink: "gran_chaco_map.png",
    imageName: "granChacoMap",
    uploadStatus: "Uploaded",
    settings: {
      dummySetting: null,
    },
    ownerName: "DanielMaas",
    collaborators: [
      "FlorianLangelaar",
      "MinghaiJiang",
      "RosalieMaas",
      "PierreOuannes",
    ],
    lastEdited: "2020/07/12",
    created: "2020/07/12",
    size: "12345",
  },
  {
    name: "Spot Amazon",
    type: "map",
    favorite: false,
    imageLink: "spot_amazon_map.png",
    imageName: "spotAmazonMap",
    uploadStatus: "Uploaded",
    settings: {
      dummySetting: null,
    },
    ownerName: "DanielMaas",
    collaborators: ["FlorianLangelaar", "MinghaiJiang", "RosalieMaas"],
    lastEdited: "2020/03/11",
    created: "2020/03/11",
    size: "1233456",
  },
  {
    name: "Harbor Sky Sat",
    type: "map",
    favorite: true,
    imageLink: "harbor_sky_sat_map.png",
    imageName: "harborSkySatMap",
    uploadStatus: "Uploading",
    settings: {
      dummySetting: null,
    },
    ownerName: "FlorianLangelaar",
    collaborators: ["RosalieMaas", "PierreOuannes"],
    lastEdited: "2020/08/08",
    created: "2020/08/08",
    size: "12334596",
  },
  {
    name: "Radar Amplitude Amsterdam",
    type: "map",
    favorite: false,
    imageLink: "radar_amplitude_amsterdam_map.png",
    imageName: "radarAmplitudeAmsterdamMap",
    uploadStatus: "Uploading",
    settings: {
      dummySetting: null,
    },
    ownerName: "FlorianLangelaar",
    collaborators: ["RosalieMaas"],
    lastEdited: "2020/03/03",
    created: "2020/03/03",
    size: "12333456",
  },
];

const mockShapes = [
  {
    name: "The Netherlands",
    type: "shape",
    favorite: false,
    imageLink: "the_netherlands_shape.png",
    imageName: "theNetherlandsShape",
    uploadStatus: "Uploaded",
    settings: {
      dummySetting: null,
    },
    ownerName: "RosalieMaas",
    collaborators: ["FlorianLangelaar", "PierreOuannes"],
    lastEdited: "2020/04/12",
    created: "2020/04/12",
    size: "133456",
  },
  {
    name: "Belgium",
    type: "shape",
    favorite: false,
    imageLink: "belgium_shape.png",
    imageName: "belgiumShape",
    uploadStatus: "Uploaded",
    settings: {
      dummySetting: null,
    },
    ownerName: "RosalieMaas",
    collaborators: [
      "FlorianLangelaar",
      "PierreOuannes",
      "DanielMaas",
      "MinghaiJiang",
      "FlorianLangelaar",
      "PierreOuannes",
      "DanielMaas",
      "MinghaiJiang",
    ],
    lastEdited: "2020/03/12",
    created: "2020/03/12",
    size: "123345695",
  },
  {
    name: "Denmark",
    type: "shape",
    favorite: false,
    imageLink: "denmark_shape.png",
    imageName: "denmarkShape",
    uploadStatus: "Uploaded",
    settings: {
      dummySetting: null,
    },
    ownerName: "RosalieMaas",
    collaborators: ["PierreOuannes", "DanielMaas"],
    lastEdited: "2020/02/12",
    created: "2020/02/12",
    size: "1233",
  },
  {
    name: "Luxembourg",
    type: "shape",
    favorite: false,
    imageLink: "luxembourg_shape.png",
    imageName: "luxembourgShape",
    uploadStatus: "Uploaded",
    settings: {
      dummySetting: null,
    },
    ownerName: "DanielMaas",
    collaborators: ["RosalieMaas"],
    lastEdited: "2020/02/12",
    created: "2020/02/12",
    size: "1233453436",
  },
  {
    name: "France",
    type: "shape",
    favorite: true,
    imageLink: "france_shape.png",
    imageName: "franceShape",
    uploadStatus: "Uploaded",
    settings: {
      dummySetting: null,
    },
    ownerName: "RosalieMaas",
    collaborators: [],
    lastEdited: "2020/11/12",
    created: "2020/11/12",
    size: "1233432456",
  },
  {
    name: "Portugal",
    type: "shape",
    favorite: true,
    imageLink: "portugal_shape.png",
    imageName: "portugalShape",
    uploadStatus: "Uploaded",
    settings: {
      dummySetting: null,
    },
    ownerName: "DanielMaas",
    collaborators: ["RosalieMaas"],
    lastEdited: "2020/02/12",
    created: "2020/02/12",
    size: "123340956",
  },
  {
    name: "Spain",
    type: "shape",
    favorite: true,
    imageLink: "spain_shape.png",
    imageName: "spainShape",
    uploadStatus: "Uploading",
    settings: {
      dummySetting: null,
    },
    ownerName: "DanielMaas",
    collaborators: ["RosalieMaas", "FlorianLangelaar", "MinghaiJiang"],
    lastEdited: "2020/09/12",
    created: "2020/09/12",
    size: "123365456",
  },
  {
    name: "Switzerland",
    type: "shape",
    favorite: true,
    imageLink: "switzerland_shape.png",
    imageName: "switzerlandShape",
    uploadStatus: "Uploaded",
    settings: {
      dummySetting: null,
    },
    ownerName: "RosalieMaas",
    collaborators: ["DanielMaas", "FlorianLangelaar", "MinghaiJiang"],
    lastEdited: "2020/07/10",
    created: "2020/07/10",
    size: "123345456",
  },
  {
    name: "Gran Chaco",
    type: "shape",
    favorite: true,
    imageLink: "gran_chaco_shape.png",
    imageName: "granChacoShape",
    uploadStatus: "Uploaded",
    settings: {
      dummySetting: null,
    },
    ownerName: "DanielMaas",
    collaborators: ["RosalieMaas"],
    lastEdited: "2020/09/29",
    created: "2020/09/29",
    size: "12346",
  },
  {
    name: "Spot Amazon",
    type: "shape",
    favorite: true,
    imageLink: "spot_amazon_shape.png",
    imageName: "spotAmazonShape",
    uploadStatus: "Uploaded",
    settings: {
      dummySetting: null,
    },
    ownerName: "DanielMaas",
    collaborators: ["FlorianLangelaar", "MinghaiJiang", "RosalieMaas"],
    lastEdited: "2020/12/05",
    created: "2020/12/05",
    size: "12343243456",
  },
  {
    name: "Harbor Sky Sat",
    type: "shape",
    favorite: false,
    imageLink: "harbor_sky_sat_shape.png",
    imageName: "harborSkySatShape",
    uploadStatus: "Uploading",
    settings: {
      dummySetting: null,
    },
    ownerName: "FlorianLangelaar",
    collaborators: [
      "DanielMaas",
      "MinghaiJiang",
      "RosalieMaas",
      "PierreOuannes",
    ],
    lastEdited: "2016/02/21 ",
    created: "2016/02/21 ",
    size: "56",
  },
  {
    name: "Radar Amplitude Amsterdam",
    type: "shape",
    favorite: true,
    imageLink: "radar_amplitude_amsterdam_shape.png",
    imageName: "radarAmplitudeAmsterdamShape",
    uploadStatus: "Uploading",
    settings: {
      dummySetting: null,
    },
    ownerName: "FlorianLangelaar",
    collaborators: [
      "DanielMaas",
      "MinghaiJiang",
      "RosalieMaas",
      "PierreOuannes",
    ],
    lastEdited: "2019/07/07",
    created: "2019/07/07",
    size: "1",
  },
];

export { mockMaps, mockShapes };
